# netlify.toml
[build]
  command = "npm run build"
  publish = "dist" # or "build" depending on your framework (Lovable usually uses dist)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
