# netlify.toml — for the site deployed at pro.yoogostudios.com

# --- Optional: your build output directory (adjust if needed) ---
# [build]
#   publish = "dist"

# ===== Project mounts (proxy subdomains into path prefixes) =====

# Canonicalize to trailing slash
[[redirects]]
  from = "/bootbucket"
  to = "/bootbucket/"
  status = 301
  force = true

# Proxy everything under /bootbucket/ to the subdomain app
[[redirects]]
  from = "/bootbucket/*"
  to = "https://pro.yoogostudios.com/:splat"
  status = 200
  force = true

# --- Add more projects by duplicating these two rules ---
# [[redirects]]
#   from = "/app2"
#   to = "/app2/"
#   status = 301
#   force = true
#
# [[redirects]]
#   from = "/app2/*"
#   to = "https://app2.yoogostudios.com/:splat"
#   status = 200
#   force = true

# ===== SPA fallback for the *main* pro site itself =====
# If the root site (pro.yoogostudios.com) is a SPA (React/Vue/etc),
# this prevents 404s on client-side routes.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
