// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://narbkktefndgxllykxph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hcmJra3RlZm5kZ3hsbHlreHBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTMyODAsImV4cCI6MjA3MDQ4OTI4MH0.BGcr-3hM_fNtHIYT322Fy7yOd5dBVv-SBKmqtl1HS3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});