// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lscseekgdiokzkvkgwya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzY3NlZWtnZGlva3prdmtnd3lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4Nzg3NDksImV4cCI6MjA3NzQ1NDc0OX0.TImQqVXfYBd4-r8OK6Z5JvDYCRM7Yf8yeBYt530CMhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});