// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfwouwamflgsierxldek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmd291d2FtZmxnc2llcnhsZGVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4ODIyODIsImV4cCI6MjA3NzQ1ODI4Mn0.GNLp5u-0UWNtD6NYN1UXyddRtsSVcmR41lLYFN_KQ3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});